version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - cd jdochoa-project-4
      - npm ci
  build:
    commands:
      - npm run build

artifacts:
  base-directory: jdochoa-project-4/build
  files:
    - '**/*'